### ISSUE TITLE
Play store changes?

### ISSUE THREAD

**Issue by peterhijma** [timtraversy/new_version#107]
Google Play store looks very different since yesterday or today?

I've got some error messages popping up now.

```
StateError: Bad state: No element
  File "list.dart", line 167, in ListMixin.firstWhere
  File "new_version.dart", line 157, in NewVersion._getAndroidStoreVersion
  File "<asynchronous suspension>"
  File "new_version.dart", line 94, in NewVersion.showAlertIfNecessary
```

So I think changes are necessary.

**Comment by timtraversy** [comment]
Yes looks like it, thanks for reporting. This will probably break the plugin until I determine the new HTML elements.

**Comment by peterhijma** [comment]
Looks like they are rolling it out gradually? Right now I see the old play store in my browser again.

**Comment by yenyichau** [comment]
When is the next update for this package? My users are facing stuck issue because of this error.

**Comment by JaviCore** [comment]
Hi, any updates regarding this issue?
Didn't even know about the store change since said breaking changes haven't reflected in my area till like yesterday/today

**Comment by mrsoehtet** [comment]
When can I get another update for this package?

**Comment by angadiumakant** [comment]
Dear author let us know whether this issue is going to fix or not. If not then we will drop this package or let us know the estimation time to fix. thousands of devices are stuck in launcher screen due to this error.

**Comment by ahmetberber** [comment]
> Dear author let us know whether this issue is going to fix or not. If not then we will drop this package or let us know the estimation time to fix. thousands of devices are stuck in launcher screen due to this error.

Agreed. I am waiting the fix too. Please let us know ASAP when you fixed.

**Comment by yenyichau** [comment]
My client thought I'm the one who cause the issue. I've removed the plugin and upload to AppStore & PlayStore. If the problem fix I I will use It back.

**Comment by nebiyuelias1** [comment]
I can confirm I'm experiencing the same problem here as everyone.

**Comment by shabeenabarde** [comment]
Same here.
Dear Author please do let us know ASAP about this fix.
Is there an alternative to this package if this won't be fixed anytime soon?

**Comment by SamarthSerpentCS** [comment]
same issue i will faced. please find the solution by author. 

Error is :

[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Bad state: No element
E/flutter ( 8554): #0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
E/flutter ( 8554): #1      NewVersion._getAndroidStoreVersion (package:new_version/new_version.dart:153:51)
E/flutter ( 8554): <asynchronous suspension>
E/flutter ( 8554): #2      SplashScreenPageState.checkAppUpdate (package:{pagename}.dart:125:41)
E/flutter ( 8554): <asynchronous suspension>

**Comment by peterhijma** [comment]
@timtraversy So apparently the store changed for more users. Any idea how to proceed? 

I looked a bit into it myself, but getting the version from the HTML page itself seems more difficult because it doesn't appear in the source code on a page load anymore. It's all javascript-driven it seems.

**Comment by SamarthSerpentCS** [comment]
@peterhijma 
From now on, remote configuration needs to be added.
But when app is uploaded to Android, you have to do it in Firebase. so this is not proper solution. 
please find what class is used by javascript? so this is easily to find this. whats version is used in latest playstore.

final additionalInfoElements = document.getElementsByClassName('hAyfc');

This class is not found. beacuse google has changed design of play store.

**Comment by shabeenabarde** [comment]
Hi. is there going to be a fix for this anytime soon?

**Comment by timtraversy** [comment]
Unfortunately, there is not an easy fix for this. The new Play Store listing design does not include the app version number. For example:
https://play.google.com/store/apps/details?id=com.google.android.apps.cloudconsole

There may be some other site where the version is listed, but someone will have to find it.

**Comment by Rodrigossff91** [comment]
actually the designer has changed a little I can't find the app version

**Comment by sbergmair** [comment]
In section „about this app“ is the version. Does this help?

**Comment by timtraversy** [comment]
Good catch. That's closer, but that HTML element is only shown after a Javascript function is triggered, so we wouldn't be able to scrape it with a simple HTTP request as we do now.

It looks like the version info is pre-fetched though, and hidden in a JS script file. So there might be a way to scrape out of there. But who knows if the format they return it in will be consistent.

**Comment by timtraversy** [comment]
Nevermind, the versions I saw in the script were the versions that different *reviews* were attached to.

**Comment by timtraversy** [comment]
https://pub.dev/packages/webdriver is a possibility.

Right now, I'm leaning towards turning off Android support and releasing a version without it. But I'll give it another day to see if anything comes up.

**Comment by timtraversy** [comment]
If anyone is up for a challenge:
1. Random app with no reviews - https://play.google.com/store/apps/details?id=com.aakenya.testapp
2. Look at page source - view-source:https://play.google.com/store/apps/details?id=com.aakenya.testapp
3. CTRL-F for the version number - currently 1.0.14
4. See if there's any possible way to extract that value from that blob of js/json

That's probably the only way.

**Comment by prakasharyaman** [comment]
import { JSOM } from 'jsdom'; 
      import axios from 'axios';

      const res = await axios('https://play.google.com/store/apps/details?id=com.yourapp');
      const dom = new JSDOM(res.data);
      const scripts = Array.from(dom.window.document.querySelectorAll('script'));
      const script = scripts.find(s => s.textContent && s.textContent.includes('/store/apps/developer'));
      const matches = script.textContent.match(versionStringRegex);
      const match = matches[0];
      const version = match.replace(/"/g, '');

      console.log(version); // '1.2.345'
It's in java script but i believe it can be converted in java ... if any one would like @timtraversy and @peterhijma

**Comment by ankitpanwar8979** [comment]
For me, some changes in _getAndroidStoreVersion worked.

```
Future<VersionStatus?> _getAndroidStoreVersion(
      PackageInfo packageInfo) async {
    final id = androidId ?? packageInfo.packageName;
    final uri =
        Uri.https("play.google.com", "/store/apps/details", {"id": "$id", "hl": "en"});
    final response = await http.get(uri);
    if (response.statusCode != 200) {
      debugPrint('Can\'t find an app in the Play Store with the id: $id');
      return null;
    }
    final document = parse(response.body);

    String storeVersion = '0.0.0';
    String? releaseNotes;

    final additionalInfoElements = document.getElementsByClassName('hAyfc');
    if (additionalInfoElements.isNotEmpty) {
      final versionElement = additionalInfoElements.firstWhere(
            (elm) => elm.querySelector('.BgcNfc')!.text == 'Current Version',
      );
      storeVersion = versionElement.querySelector('.htlgb')!.text;

      final sectionElements = document.getElementsByClassName('W4P4ne');
      final releaseNotesElement = sectionElements.firstWhereOrNull(
            (elm) => elm.querySelector('.wSaTQd')!.text == 'What\'s New',
      );
      releaseNotes = releaseNotesElement
          ?.querySelector('.PHBdkd')
          ?.querySelector('.DWPxHb')
          ?.text;
    } else {
      final scriptElements = document.getElementsByTagName('script');
      final infoScriptElement = scriptElements.firstWhere(
            (elm) => elm.text.contains('key: \'ds:4\''),
      );

      final param = infoScriptElement.text.substring(20, infoScriptElement.text.length - 2)
          .replaceAll('key:', '"key":')
          .replaceAll('hash:', '"hash":')
          .replaceAll('data:', '"data":')
          .replaceAll('sideChannel:', '"sideChannel":')
          .replaceAll('\'', '"')
          .replaceAll('owners\"', 'owners');
      final parsed = json.decode(param);
      final data =  parsed['data'];

      storeVersion = data[1][2][140][0][0][0];
      releaseNotes = data[1][2][144][1][1];
    }

    return VersionStatus._(
      localVersion: _getCleanVersion(packageInfo.version),
      storeVersion: _getCleanVersion(forceAppVersion ?? storeVersion),
      appStoreLink: uri.toString(),
      releaseNotes: releaseNotes,
    );
  }
```

Still not sure if play store HTML will be consistent or not but it worked for now.

**Comment by shadi-danhash** [comment]
A fast solution..

```
/// Android info is fetched by parsing the html of the app store page.
  Future<VersionStatus?> _getAndroidStoreVersion(
      PackageInfo packageInfo) async {
    final id = androidId ?? packageInfo.packageName;
    final uri =
    Uri.https("play.google.com", "/store/apps/details", {"id": "$id"});
    final response = await http.get(uri);
    if (response.statusCode != 200) {
      debugPrint('Can\'t find an app in the Play Store with the id: $id');
      return null;
    }
    print('time a ${DateTime.now()}');
    final exp =RegExp(r"\d+[.]\d+[.]\d+");
    var match = exp.firstMatch(response.body)!;
    var storeVersion = response.body.substring(match.start , match.end);
    print('time b ${DateTime.now()}');
    print('VERSION $storeVersion');
    return VersionStatus._(
      localVersion: packageInfo.version,
      storeVersion: forceAppVersion ?? storeVersion,
      appStoreLink: uri.toString(),
      releaseNotes: "TODO",
    );
  }

```

**Comment by Sapnajain01** [comment]
I'm getting the same error

**Comment by kldawad** [comment]
> I'm getting the same error is there any solution because user can't visit to my application it stuck on the splash screen and my application is live ![Anaaj issue](https://user-images.githubusercontent.com/43822881/170939010-49bf9bb6-0d73-4426-922b-036b2556dad7.png)

same here

**Comment by timtraversy** [comment]
To those this is breaking: you will have to release a new version of your apps to fix this issue. I would recommend just doing that now, and removing the calls to this plugin. This was an unforseen change in the Play Console, we're working on a fix.

**Comment by timtraversy** [comment]
Nice concepts above, thank you!

@prakasharyaman - This is a clever idea, but people format there versions different ways. Also, the HTML contains multiple version strings from past versions, so we would have to add some logic to fix that as well.

@ankitpanwar8979  - This is my preferred solution. The nested array doesn't seem like it will remain stable as the Play site changes, but best we can do for now.

**Comment by glngrizkyy** [comment]
> ### [3 days ago](#issuecomment-1140214179) •

can u explain code _getCleanVersion is what for?

**Comment by prakasharyaman** [comment]
# Try This
## Works for now
       public function getAndroidVersion(string $storeUrl): string
       {
       $html = file_get_contents($storeUrl);
           $matches = [];
           preg_match('/\[\[\[\"\d+\.\d+\.\d+/', $html, $matches);
           if (empty($matches) || count($matches) > 1) {
               throw new Exception('Could not fetch Android app version info!');
           }
           return substr(current($matches), 4);
       }

**Comment by vinayakyengandul** [comment]
@timtraversy same issue is facing ( **Bad state: No element** )
Now what is the solution for it.

**Comment by eramitsharma957** [comment]
> Google Play store looks very different since yesterday or today?
> 
> I've got some error messages popping up now.
> 
> ```
> StateError: Bad state: No element
>   File "list.dart", line 167, in ListMixin.firstWhere
>   File "new_version.dart", line 157, in NewVersion._getAndroidStoreVersion
>   File "<asynchronous suspension>"
>   File "new_version.dart", line 94, in NewVersion.showAlertIfNecessary
> ```
> 
> So I think changes are necessary. You can find the version of the app in a modal @ "About this app ->"

Please provide me solution ASAP in  "Bad state: No element"

**Comment by ankitpanwar8979** [comment]
> > ### [3 days ago](#issuecomment-1140214179) •
> 
> can u explain code _getCleanVersion is what for?

Check this function
https://github.com/timtraversy/new_version/blob/a71a9b8428cb1fd5fe809806f72356d4e1c41bb4/lib/new_version.dart#L117

**Comment by X-SLAYER** [comment]
I have a similar package and am using regex to get the version from the play store you can check it here 
[flutter_app_version_checker](https://github.com/X-SLAYER/app_version_checker/blob/f865b99b31525cb899cfe0a2ebb140f358bdea36/lib/flutter_app_version_checker.dart#L95)
```dart
newVersion = RegExp(r',\[\[\["([0-9,\.]*)"]],')
```

**Comment by appstute-sachin** [comment]
Facing same issue since few days and this has broken our force update functionality on android. Can we expect this issue to be resolved in upcoming plugin version?

**Comment by utarn** [comment]
This is my code.
```
  Future<VersionStatus?> _getAndroidStoreVersion(PackageInfo packageInfo) async {
    final id = androidId ?? packageInfo.packageName;
    final uri = Uri.https("play.google.com", "/store/apps/details", {"id": id});
    final response = await http.get(uri);
    if (response.statusCode != 200) {
      debugPrint('Can\'t find an app in the Play Store with the id: $id');
      return null;
    }

    final document = parse(response.body);
    var releaseNotes = document.querySelector('div[itemprop="description"]')!.innerHtml;
    final storeVersion = RegExp(r',\[\[\["([0-9,\.]*)"]],').firstMatch(response.body)!.group(1);

    return VersionStatus._(
      localVersion: _getCleanVersion(packageInfo.version),
      storeVersion: _getCleanVersion(storeVersion ?? '0.0.0'),
      appStoreLink: uri.toString(),
      releaseNotes: releaseNotes,
    );
  }
```

**Comment by timtraversy** [comment]
I don't have the environment set up to test it, but `0.3.1` should be live with a fix.
