### ISSUE TITLE
Bad element

### ISSUE THREAD

**Issue by FrankNsougui** [timtraversy/new_version#115]
Google play has updated its site so the package no longer works, please check this

**Comment by snghnishant** [comment]
Yup not working anymore! Here are the crashlytics logs

```text
I/flutter (31058): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (31058): Bad state: No element
I/flutter (31058): 
I/flutter (31058): #0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
I/flutter (31058): #1      NewVersion._getAndroidStoreVersion (package:new_version/new_version.dart:157:51)
I/flutter (31058): <asynchronous suspension>
I/flutter (31058): #2      _HomeScreenState.checkForNewVersion (package:stratzy/Screens/HomeScreen/landing_page.dart:155:20)
I/flutter (31058): <asynchronous suspension>
I/flutter (31058): ----------------------------------------------------
```
