### ISSUE TITLE
SocketException: OS Error address = play.google.com

### ISSUE THREAD

**Issue by mdmota** [timtraversy/new_version#67]
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: SocketException: OS Error: No route to host, errno = 113, address = play.google.com, port = 42788. Error thrown home_page_getData.
       at _HttpClient.openUrl(_HttpClient.java)
       at IOClient.send(IOClient.java:35)
       at BaseClient._sendUnstreamed(BaseClient.java:93)
       at BaseClient.get(BaseClient.java:27)
       at get.<fn>(get.java:46)
       at ._withClient(.java:164)
       at .get(.java:46)
       at NewVersion._getAndroidStoreVersion(NewVersion.java:144)
       at NewVersion.getVersionStatus(NewVersion.java:103)
       at _HomePageState._basicStatusCheck(_HomePageState.java:85)
       at _HomePageState.getData(_HomePageState.java:177)
       at _FutureBuilderState._subscribe.<fn>(_subscribe.java)
```

**Comment by timtraversy** [comment]
What command threw this error? Are you still getting it?

**Comment by mdmota** [comment]
`var status = await newVersion.getVersionStatus();`

does not happen to everyone. seems to be intermittent.

**Comment by dreadjr** [comment]
I see those errors in crashlytics very often.

**Comment by timtraversy** [comment]
This is unlikely an issue with this plugin - that error usually indicates an issue with your internet connection.

**Comment by timtraversy** [comment]
I'm pretty certain this issue only arises when the device is offline. A possible enhancement for this is in #73, which could be implemented.
