### ISSUE TITLE
Error when checking androidstore

### ISSUE THREAD

**Issue by choisunghwa** [timtraversy/new_version#72]
It had been well used in the past. but today...

Future<VersionStatus?> _getAndroidStoreVersion(
...
	final document = parse(response.body);  <- here!! 

		It's taking an unbelievably long time, and it seems to be an error.
		
		Is it my problem? or google store problem?
		Does anyone have the same problem?

	
		
E/flutter (17394): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: No element
E/flutter (17394): #0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
E/flutter (17394): #1      NewVersion._getAndroidStoreVersion (package:new_version/new_version.dart:152:51)

**Comment by choisunghwa** [comment]
I tested it today and it works. Maybe it's not a package problem, it's a different problem.
