### ISSUE TITLE
Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by rhowelp** [timtraversy/new_version#98]
I am trying to implement this package but whenever I try to check and hot reload. I get this error.

```
   E/flutter (13079): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info)
    E/flutter (13079): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:175
    E/flutter (13079): <asynchronous suspension>
    E/flutter (13079): #1      MethodChannel.invokeMapMethod
package:flutter/…/services/platform_channel.dart:377
    E/flutter (13079): <asynchronous suspension>
    E/flutter (13079): #2      MethodChannelPackageInfo.getAll     (package:package_info_plus_platform_interface/method_channel_package_info.dart:13:17)
    E/flutter (13079): <asynchronous suspension>
    E/flutter (13079): #3      PackageInfo.fromPlatform (package:package_info_plus/package_info_plus.dart:36:26)
    E/flutter (13079): <asynchronous suspension>
    E/flutter (13079): #4      NewVersion.getVersionStatus (package:new_version/new_version.dart:104:31)
    E/flutter (13079): <asynchronous suspension>
    E/flutter (13079):
```

Here is my code: 
  
    
    final newVersion = NewVersion(
      androidId: androidId,
      iOSId: iosId,
    );

    newVersion.getVersionStatus().then((versionStatus) {
      print("My Version: " + versionStatus!.localVersion);
      print("Store Version: " + versionStatus.storeVersion);
      if (versionStatus.canUpdate) {
        newVersion.showUpdateDialog(
            dialogTitle: 'A new version is available',
            dialogText: 'Testing',
            updateButtonText: 'Update',
            context: context,
            versionStatus: versionStatus,
            allowDismissal: false);
      }
    });

Flutter Doctor:
```
    [√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1586], locale en-US)
    • Flutter version 2.10.3 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\rhowe\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)   
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe     

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code, 64-bit edition (version 1.60.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] Connected device (4 available)
    • vivo 1606 (mobile) • 596af440 • android-arm    • Android 6.0.1 (API 23)
    • Windows (desktop)  • windows  • windows-x64    • Microsoft Windows [Version 10.0.19044.1586]
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 99.0.4844.84
    • Edge (web)         • edge     • web-javascript • Microsoft Edge 99.0.1150.55

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by laloprieto** [comment]
Hi, rhowelp
How did you solve the error?

**Comment by rhowelp** [comment]
> Hi, rhowelp How did you solve the error?

Hello!
What I did was stop the debugging, `flutter clean` and `flutter pub get` then run again.
But I guess stop and run again can solve it. :)
